![](https://media.giphy.com/media/ccRMvuh3PeuSGgOWVx/giphy.gif)

Remember the rules of ~Fight~ Code Club:
1. ALWAYS DOCUMENT
2. Cite resources that you use (paste links)
3. Include the names people who you worked with
4. Be neat and organized

# Question 1
Identify the lists below. If they are a list, explain how you know this (syntax or function that you used). If it is not a list, tell me what it is and explain how you know this.

1. `np.std()`
2. `print(['hello', 67, 85, '25'])`
3. `['fall','spring','summer','winter']`
4. `{'a':1, 'b':2, 'c': 3, 'd':4, 'e':5, 'g':6}`
5. `[[1,45],[56,89],[88,45]]`
6. `('August','September', 'October','November','December')`

In [2]:
#1. np.std() is not a list 
#it is used to compute the standard deviation.
#This function returns the standard deviation of the elements
#I know this from the lecture slides as it is one of the commands 

In [7]:
print(['hello', 67, 85, '25'])
#this is not a list, it will only become a list after you run the command. The Result is a list.

['hello', 67, 85, '25']


In [2]:
list3 = ['fall','spring','summer','winter']
print(type(list3))
#I used the type element command to see if it is a list. And it is a list. Command used taken from https://www.w3schools.com/python/python_lists.asp

<class 'list'>


In [5]:
list4 = {'a':1, 'b':2, 'c': 3, 'd':4, 'e':5, 'g':6}
print(type(list4))
#using the print type function, we can see that it is a dictionary. Dictionary are not lists as they cannot be duplicates
#and are unordered. Command used taken from https://www.w3schools.com/python/python_lists.asp

<class 'dict'>


In [3]:
list5 = [[1,45],[56,89],[88,45]]
print(type(list5))
#I used the print type command again to see if it is a list. And it is a list. Command used taken from https://www.w3schools.com/python/python_lists.asp

<class 'list'>


In [6]:
list6 = ('August','September', 'October','November','December')
print(type(list6))
#I used the print type command to see if it is a list and it is a tuple. Tuples are not list as they are immutable and surrounded 
#by the regular bracket instead of the square brackets. Command used taken from https://www.w3schools.com/python/python_lists.asp

<class 'tuple'>


## Question 2

1. Write a python script that prints 'even' for every even number 
2. and creates a new list of even numbers (using list comprehension)

using the series: [1,2,3,7,9,34,56,70,90,123,136,148,156] 

In [13]:
series = [1,2,3,7,9,34,56,70,90,123,136,148,156] #given the series, write a python script that prints 'even' for every even number 
for n in series:        #I'm setting the specifics condition 
    if n % 2 ==0:       #here if n divides by 2 and there are no remainder, it means it is even. I used the notes from lecture slides. 
        print("{} is even".format(n)) #print the message n is even, to take sure that the number is printed as well as the even, I used format function.
                                      #The format() function returns a formatted representation of a given value specified by the format specifier.taken from  https://www.programiz.com/python-programming/methods/built-in/format

2 is even
34 is even
56 is even
70 is even
90 is even
136 is even
148 is even
156 is even


In [12]:
series = [1,2,3,7,9,34,56,70,90,123,136,148,156] #given the series, creates a new list of even numbers (using list comprehension)
even = [n for n in series if n % 2 ==0]  #using the list comprehension function, to create a list of even numbers.
print("list of even number is = {}".format(even))    #like before the format() function returns a formatted representation of a given value specified by the format specifier. 
                                                    #Here I want to show the whole as a list of numbers so i put the string List of even numbers at front 
                                                    #and the format(even) helps to put all the number as the list that follows taken from  https://realpython.com/list-comprehension-python/

list of even number is = [2, 34, 56, 70, 90, 136, 148, 156]


## Question 3

Write a script that skips vowels from the following string: "Python is for everyone!"

Be sure that this outputs in one string or list in one line.

In [38]:
# Python program to remove vowels from a string
def rem_vowel(string): #using the definition function, we define it as rem_vowel for a string 
    vowels = ['a','e','i','o','u']  # we make a list of all the vowels so that we can remove them 
    result = [letter for letter in string if letter.lower() not in vowels] #command to go letter by letter and see if the letter is in the vowel list if it is in the vowel list, print if not in the list
    result = ''.join(result)    #use the.join(result) so that the final product is one whole sentence instead of just a list with individual items as letters. 
    print(result)               #command to print the result 
string = "Python is for everyone!"     #now we define the string. where the string is "Python is for everyone!"
rem_vowel(string)                      #now we use the rem_vowel command that was defined above and get the final product 

Pythn s fr vryn!


## Question 4

Use a numpy function that randomly generates numbers in an array that has the shape(8,8)

In [61]:
import numpy as np  #import numpy under the np alias. Create an alias with the as keyword while importing: Now the NumPy package can be referred to as np instead of numpy.
rand_int = np.random.randint(1,90,(8,8)) # define rand_int as the array and set the outputs as an 8x8 array filled with random numbers 
print(rand_int)                  #print the random array that randomly generates numbers in an array that has the shape(8,8) 

[[22 23 53  3 23 43 36 71]
 [45 43 69 22 41 12 73  9]
 [17 71 61 54 58 79 40 30]
 [15 48 49 81 29 65 89 51]
 [ 8  5 26 32 60 84 34 71]
 [23 22 40 34 19 78 53 54]
 [40 15 15 76 16  8 14 19]
 [48 54 57  7 39 73 83 36]]


## Question 5
Using the following arrays:

a = np.array([45,86,78,300,586,686,486,794,486,58,77,93,55,83,136])

b = np.array([45,67,239,555,597,264,908,562,44,58,39,57,62,58,224])

Write a python code using **numpy** that:
   1. calculates the difference between the minimum and maximum number for each earray
   2. calculates the 75th percentile for each array
   3. calculates the mean and standard deviation for each array
   4. calculates the correlation coefficient between the two arrays
    
Please document what those numbers are in your answer. 

Hint: the functions for these statistics can easily be found in the lecture slides and any reference guide to python

In [3]:
#calculate the difference between the min and max number for each array: first to calculate the a array 
import numpy as np       #import numpy under the np alias. 
a = np.array([45,86,78,300,586,686,486,794,486,58,77,93,55,83,136]) #copy the array from above 
a.max()-a.min() #use the function to find the max which is 794- the min which is 45 

749

In [13]:
#calculate the difference between the min and max number for each array: first to calculate the a array
import numpy as np         #import numpy under the np alias. 
b = np.array([45,67,239,555,597,264,908,562,44,58,39,57,62,58,224]) #copy the array from above 
b.max()-b.min() #use the function to find the max which is 908 the min which is 39 

869

In [14]:
#calculates the 75th percentile for each array
#calculate A first: 
import numpy as np         #import numpy under the np alias. 
a = np.array([45,86,78,300,586,686,486,794,486,58,77,93,55,83,136])         #define the array that you want to calcualte 
p = np.percentile(a, 75)                            #define another value, p, and use the percentile command to find 75th the command used is taken from https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
print(p)                #print the outcome 

486.0


In [12]:
#calculates the 75th percentile for each array
#caculate for B array
import numpy as np         #same as above, import numpy under the np alias. 
b = np.array([45,67,239,555,597,264,908,562,44,58,39,57,62,58,224])         #define the array that you want to calcualte 
p = np.percentile(a, 75)                            #define another value, p, and use the percentile command to find 75th the command used is taken from https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
print(p)                #print the outcome 

486.0


In [19]:
#calculates the mean for A array 
import numpy as np         #import numpy under the np alias. 
a = np.array([45,86,78,300,586,686,486,794,486,58,77,93,55,83,136])         #define the array that you want to calcualte 
np.mean(a)                #use the command np.mean(a) to find the mean of a array. taken from https://numpy.org/doc/stable/reference/generated/numpy.mean.html

269.93333333333334

In [22]:
#calculates the standard deviation for A array 
import numpy as np         #import numpy under the np alias. 
a = np.array([45,86,78,300,586,686,486,794,486,58,77,93,55,83,136])         #define the array that you want to calcualte 
np.std(a)        #use the command np.mean(a) to find the std of a array. taken from https://numpy.org/doc/stable/reference/generated/numpy.mean.html

255.04469325111543

In [23]:
#calculates the mean for B array 
import numpy as np         #import numpy under the np alias. 
b = np.array([45,67,239,555,597,264,908,562,44,58,39,57,62,58,224])               #define the array that you want to calcualte 
np.mean(b)                #use the command np.mean(b) to find the mean of b array. taken from https://numpy.org/doc/stable/reference/generated/numpy.mean.html

251.93333333333334

In [24]:
#calculates the standard deviation for B array 
import numpy as np         #import numpy under the np alias. 
b = np.array([45,67,239,555,597,264,908,562,44,58,39,57,62,58,224])               #define the array that you want to calcualte 
np.std(b)            #use the command np.std(b) to find the std of b array. taken from https://numpy.org/doc/stable/reference/generated/numpy.mean.html

265.0120668112219

In [28]:
#calculates the correlation coefficient between the two arrays
import numpy as np         #import numpy under the np alias. 
a = np.array([45,86,78,300,586,686,486,794,486,58,77,93,55,83,136]) #define the first array, a
b = np.array([45,67,239,555,597,264,908,562,44,58,39,57,62,58,224]) #define the second array, b
np.corrcoef(a, b)                 #use the command np.corrcoef(a,b) to find the correlation coefficient taken from   https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

array([[1.        , 0.65399586],
       [0.65399586, 1.        ]])

## Question 6

1. Import the data set "moveidataset.csv"
2. Find out the average revenue for movies that start with the letter "s"
3. Create a for loop that calculates the average earnings for movies that start with each letter of the alphabet (ie average for movies that start with a, average for movies that start in b).  Make sure the averages are stored in one list.
4. Slice the above list so that you show the average earnings for movies that start with the letter l through p.
5. Write a for loop that prints out the first five movies of each letter of the alphabet. Use a nested loop.
6. What is the difference in average movie earnings between movies that were turned into a novel compared to movies that were note turned into a novel (ie a movie that that was turned into novel is where novel = 1)?
7. Create a new variable (name it whatever you want) the is the ratio of revenue over budget.
8. Export your new dataset into your repo folder with the name "newmovieds.csv"

In [5]:
import pandas as pd                #command code used to import the package 
import numpy as np                 #import numpy under the np alias. 
wjp = pd.read_csv(r"C:\Users\owenl\Documents\GitHub\RL\assignment-1-code-check-rl05262n\moviedataset.csv")       #command code to read the package and the path the package is in. 
df = pd.read_csv('moviedataset.csv')                #import the dataset and define it as df for future simple functions 
df.drop('Unnamed: 0', axis = 1, inplace = True)     #drop the column that is second to the right to have a clearer data to look at
df['Film'] = df['Film'].str.lower() #convert all films  into lower case so that its easier to do the string start with function 
movieswiths = df[df['Film'].str.startswith('s', na=False)]     #set the condition to separate and filter specifically films that starts with  and eliminate all the others. 
movieswiths               #show the movies that start with s on the data table  #functions taken from https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html and lecture 

Film     Budget    Revenue  Novel
1052            s.w.a.t.   80000000  116643346    0.0
1053          safe haven   28000000   97594140    1.0
1054          safe house   85000000  208076205    0.0
1055              sahara  130000000  119269486    1.0
1056                salt  110000000  293329073    0.0
...                  ...        ...        ...    ...
1206  sweet home alabama   30000000  180622424    0.0
1207          swing vote   21000000   17600000    0.0
1208      swiss army man    3000000    4210454    0.0
1209        sydney white   16500000   13620075    0.0
1210             syriana   50000000   94000000    0.0

[159 rows x 4 columns]

In [6]:
movieswiths['Revenue'].mean()  #calculate mean from the Revenue Column taken from Lecture Slides 

183053896.7798742

In [20]:
#to create a for loop that calculate average earning for the movies starts with each alpabets and one list
from string import ascii_lowercase      #this function helps to put all the ones that have potentially Capital letters into lower case 
                                        #It returns lowercase letters from a to z as a string. The returned string from this constant is not locale-dependent and will not change. Taken from https://www.codespeedy.com/python-string-ascii_lowercase/
letter_avg = pd.DataFrame(columns = ['Letter', 'Average Revenue'])   #set what we want as letter_avg and define the two columns in our data frame as letter and average revenue taken from https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html
for i in ascii_lowercase:                  #set the condition for our for loop, for every letter, i, in lowercase that was converted, the following applies.
    movies = df[df['Film'].str.startswith(i, na=False)]         #using the Python standard library string method, set the condition that if the str under film starts with any letter, i, the data will specifically turn any na to be False instead of NaN.(a problem I ran into) Taken from https://pandas.pydata.org/docs/reference/api/pandas.Series.str.startswith.html
    a_series = pd. Series([i, round(movies['Revenue'].mean(),2)], index = letter_avg.columns) #define the new series as the starting letter, i, and the mean of all the movies revenue under two decimals.and the index/column is letter_avg.columns
    letter_avg = letter_avg.append(a_series, ignore_index=True)   #define letter_avg and use the function append to add up all the movie averages we calculated from above. Since Append rows of other to the end of caller, returning a new object. We use the ignore_index function, which is false at default, and make it True, so that the resulting axis will be labeled 0, 1, …, n - 1. taken from https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.append.html

In [21]:
letter_avg['Average Revenue'] = letter_avg['Average Revenue'].astype(int)         #define letter_avg Average revenue column as a interger type so that there are no float values. 
letter_avg                #show the data/table Letter_avg Below 

Letter  Average Revenue
0       a        141851810
1       b        115126954
2       c        139677697
3       d        144954632
4       e        107740125
5       f        191590776
6       g        171024419
7       h        200709787
8       i        256005429
9       j        157392149
10      k        222097121
11      l        110810060
12      m        185046766
13      n        141803391
14      o        111932473
15      p        174440945
16      q        148462543
17      r        148406492
18      s        183053896
19      t        170073302
20      u        100198027
21      v        111626354
22      w        128565490
23      x        495568821
24      y        103577446
25      z        203026908

In [9]:
#Slice the above list so that you show the average earnings for movies that start with the letter l through p.
slice_df = pd.DataFrame(columns = ['Letter','Average Revenue'])          #define the slice as slice_df and separate the list above by slicing and defining the columns letter and average revenue. Taken from https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html
for i in range(ord('i'), ord('p') + 1):                                  #set the forloop condition for the letters we want. For letter i in the range letter i to letter p+1 so that we include p,I used ord so that it returns the interger that represents letter i through letter p. 
    slice_df = slice_df.append(letter_avg[letter_avg['Letter'].str.startswith(chr(i), na=False)])  #define new slice_df as add up all the letter averages starting with if the string  of the letter starts with character i/letter i. set na=false so that the data will specifically turn any na to be False instead of NaN.

In [10]:
slice_df                      #show the slice 

Letter Average Revenue
8       i       256005429
9       j       157392149
10      k       222097121
11      l       110810060
12      m       185046766
13      n       141803391
14      o       111932473
15      p       174440945

In [19]:
#Write for loop that prints first 5 movies of each letters of alphabets
df = df.sort_values(by= ['Film'], ascending = True) #to make sure that the films are in order, we sort by ascending so that the letters are a to z. 
from string import ascii_lowercase           #same as above, to make sure all the films are in lower letters, we use the command from string import lowercase. 
for i in ascii_lowercase:                    #set the for loop for the condition that for each lower case letter of the alphabete, i, the movies will go through the loop below
    movies = df[df['Film'].str.startswith(i, na=False)]    #define movies as the datafunction where under the column string Film, if the string starts with letter, i, any letter in the alphbete.  since like above,we set na=flase so that the data will specifically turn any na to be False instead of NaN.Taken from https://pandas.pydata.org/docs/reference/api/pandas.Series.str.startswith.html
    movies.reset_index(drop =True, inplace = True)       #use c.reset index to reset the index as well as dropping the old index. the drop is there to make sure we avoid the old index being added as a column and inplace is there to replace the old column taken from https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html
    print(movies.loc[0:4,'Film'].values)          #Print each of the first 5 movies loc[0:4] that are listed under Film. where 0 is the first movie, 1 is the second etc
                                                  #i used loc to make sure that it outputs a single label, returning the row as a Series. taken from https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

['a cinderella story' 'a cure for wellness' "a dog's purpose"
 'a good day to die hard' 'a good year']
['babel' 'baby driver' 'baby mama' 'babylon a.d.' 'bad boys ii']
['cabin fever' 'calendar girls' 'capitalism: a love story' 'capote'
 'captain america: civil war']
['daddy day camp' 'daddy day care' "daddy's home" 'dallas buyers club'
 'dan in real life']
['eagle eye' 'earth to echo' 'eastern promises' 'easy a' 'eat pray love']
['fahrenheit 9/11' 'failure to launch' 'fantastic four' 'fantastic four'
 'fantastic mr. fox']
['g-force' 'g.i. joe: retaliation' 'g.i. joe: the rise of cobra' 'gamer'
 'gangs of new york']
['hacksaw ridge' 'hail, caesar!' 'hall pass' 'halloween: resurrection'
 'hancock']
['i am legend' 'i am number four' "i don't know how she does it"
 'i know who killed me' 'i love you, man']
['j. edgar' 'jack and jill' 'jack reacher' 'jack reacher: never go back'
 'jack ryan: shadow recruit']
['k-19: the widowmaker' 'katy perry: part of me' 'keanu'
 'keeping up with the jone

In [14]:
#What is the difference in average movie earnings between movies that were turned into a novel compared to movies that were note turned into a novel (ie a movie that that was turned into novel is where novel = 1)?
movies_without_novel = df[df['Novel'] == 0] #group all the movies that were not turned into novels, ie, where under column novel is 0,
movies_without_novel                   #show all the movies that were not turned into novels, where novel = 0

Film     Budget     Revenue  Novel
0     (500) days of summer    7500000    60722734    0.0
1      10 cloverfield lane   15000000   108286421    0.0
2                12 rounds   20000000    17280326    0.0
4                127 hours   18000000    35692920    0.0
5           13 going on 30   37000000    96455697    0.0
...                    ...        ...         ...    ...
1756                zodiac   65000000    84785914    0.0
1757            zombieland   23600000   102391382    0.0
1758             zookeeper   80000000   169852759    0.0
1759           zoolander 2   50000000    55969000    0.0
1761              zootopia  150000000  1023784195    0.0

[1435 rows x 4 columns]

In [15]:
movies_with_novel = df[df['Novel'] == 1]       #group all the movies that were turned into novels, ie, where under column novel is 1, 
movies_with_novel                               #show all the movies that were turned into novels, where novel = 1

Film     Budget    Revenue  Novel
3         12 years a slave   20000000  187000000    1.0
32    90 minutes in heaven    5000000    4842699    1.0
36         a dog's purpose   22000000  194647323    1.0
38             a good year   35000000   42064105    1.0
48       a most wanted man   15000000   31554855    1.0
...                    ...        ...        ...    ...
1709   what's your number?   20000000   30426096    1.0
1715               whip it   15000000   16633035    1.0
1728         winter's tale   60000000   30800231    1.0
1736           world war z  200000000  531865000    1.0
1760                  zoom   35000000   12506188    1.0

[327 rows x 4 columns]

In [23]:
novel_df = pd.DataFrame({'Movies Category':['Movies With novel', 'Movies Without novel'], 'Earning Average':[round(movies_with_novel['Revenue'].mean(),2),round(movies_without_novel['Revenue'].mean(),2)]}) #set a new data frame 
                                                                                                                                                                                                            #and define the column as movies category and earning averages where under movies 
                                                                                                                                                                                                            #there are two types of strings as rows, movies with novel or movie with novel
                                                                                                                                                                                                            #define the earning average column with two datasets, averages from movies with and without novel
                                                                                                                                                                                                            #and take the mean of the previous data set of both movies with/without novels under revenue and round it to 2 decimals 
novel_df['Earning Average'] = novel_df['Earning Average'].astype(int)          #define the data frame with string earning average and change the type to interger instead of floats with decimals. taken from https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html
novel_df             #show the result

Movies Category  Earning Average
0     Movies With novel        179383963
1  Movies Without novel        157337143

In [17]:
#Cost revenue ratio 
df['revenue ratio'] = df['Budget']/df['Revenue'] #now to caculate the cost revenue ratio we define it as Cost revenue ratio = cost of revenue / total revenue we divide the whole column under the string budget by the whole column under string revnue 
df                                              #to show the datafunction that we just modified 

Film     Budget     Revenue  Novel  revenue ratio
0     (500) days of summer    7500000    60722734    0.0       0.123512
1      10 cloverfield lane   15000000   108286421    0.0       0.138522
2                12 rounds   20000000    17280326    0.0       1.157386
3         12 years a slave   20000000   187000000    1.0       0.106952
4                127 hours   18000000    35692920    0.0       0.504302
...                    ...        ...         ...    ...            ...
1757            zombieland   23600000   102391382    0.0       0.230488
1758             zookeeper   80000000   169852759    0.0       0.470996
1759           zoolander 2   50000000    55969000    0.0       0.893352
1760                  zoom   35000000    12506188    1.0       2.798615
1761              zootopia  150000000  1023784195    0.0       0.146515

[1762 rows x 5 columns]

In [18]:
df.to_csv('newmovieds.csv') #Export the new dataset into my repo folder with the name "newmovieds.csv" function taken from Lecture slide.